name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        cache-dependency-path: 'backend/yarn.lock'

    - name: Install dependencies
      run: cd backend && yarn install --frozen-lockfile

    - name: Run linter
      run: cd backend && yarn lint

    - name: Check formatting
      run: cd backend && yarn format:check

    - name: Build TypeScript
      run: cd backend && yarn build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: backend/dist
        retention-days: 1

  test:
    name: Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: 'backend/yarn.lock'

    - name: Install dependencies
      run: cd backend && yarn install --frozen-lockfile

    - name: Run tests
      run: cd backend && yarn test

    - name: Generate coverage report (Node 20 only)
      if: matrix.node-version == 20
      run: cd backend && yarn test:coverage

    - name: Upload coverage to Codecov (Node 20 only)
      if: matrix.node-version == 20
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./backend/coverage/lcov.info
        flags: unittests
        name: codecov-${{ matrix.node-version }}
        fail_ci_if_error: false

    - name: Upload test logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs-node-${{ matrix.node-version }}
        path: backend/logs/test-*.log
        retention-days: 7
